- hosts: all
  become: yes
  tasks:
    - name: Check if WordPress container exists and remove it
      ansible.builtin.shell: docker inspect wordpress_container
      register: container_inspect
      ignore_errors: yes
    
    - name: Remove existing WordPress container if it exists
      ansible.builtin.docker_container:
        name: wordpress_container
        state: absent
      when: container_inspect|success

    - name: Create Docker Compose directory
      file:
        path: /root/docker-wordpress
        state: directory

    - name: Create Docker Compose file
      copy:
        dest: /root/docker-wordpress/docker-compose.yml
        content: |
          version: '3.1'

          services:
            wordpress:
              image: wordpress:6.5.4
              restart: always
              ports:
                - 8080:80
              environment:
                WORDPRESS_DB_HOST: db
                WORDPRESS_DB_USER: wordpress
                WORDPRESS_DB_PASSWORD: wordpress
                WORDPRESS_DB_NAME: wordpress
              cap_add:
                - NET_ADMIN

            db:
              image: mysql:5.7
              restart: always
              environment:
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wordpress
                MYSQL_PASSWORD: wordpress
                MYSQL_ROOT_PASSWORD: somewordpress

    - name: Install iproute2 package
      ansible.legacy.command:
        cmd: docker exec wordpress_container apt-get update && apt-get install -y iproute2
        creates: /usr/sbin/ip
        environment:
          DEBIAN_FRONTEND: noninteractive

    - name: Start WordPress with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /root/docker-wordpress
